language: python
python:
  - "3.6"
script: pytest ./tests/
before_deploy:
  - sudo apt-get -q update
  - sudo pip install awscli
  - sudo apt-get install -y jq
  - wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
  - sudo unzip -d /usr/local/bin/ terraform_0.11.3_linux_amd64.zip
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g --silent @angular/cli
  - cd ./frontend/; npm install; cd ../
deploy:
  provider: script
  script: ./deploy.sh dev
  on:
    branch:
      - issue-43-ng-again
