dist: xenial
language: python
python:
  - "3.7"
script:
  - pytest ./backend/tests/
before_deploy:
  - sudo apt-get -q update
  - sudo pip install awscli
  - wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
  - sudo unzip -d /usr/local/bin/ terraform_0.11.14_linux_amd64.zip
  - nvm install 10
deploy:
  provider: script
  script: ./deploy.sh prod
  on:
    branch:
      - master
