service: retrospective


provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  stage: ${env:ENVIRONMENT}
  memorySize: 128
  deploymentBucket:
    name: serverless-deploy-485419608727
  iamManagedPolicies:
    - ${env:DATABASE_POLICY}
  environment:
    ENVIRONMENT: ${env:ENVIRONMENT}


package:
  exclude:
    - ./**
  include:
    - backend/**


functions:
  createRetro:
    handler: backend.api.views.generic.retro.create
    events:
      - http:
          path: /api/retro
          method: post

  moveRetro:
    handler: backend.api.views.generic.retro.move
    events:
      - http:
          path: /api/retro/{retro_id}
          method: put

  getRetro:
    handler: backend.api.views.generic.retro.get
    events:
      - http:
          path: /api/retro/{retro_id}
          method: get

  addParticipant:
    handler: backend.api.views.generic.user.add_participant
    events:
      - http:
          path: /api/retro/{retro_id}/user
          method: post

  markAsReady:
    handler: backend.api.views.generic.user.mark_as_ready
    events:
      - http:
          path: /api/retro/{retro_id}/user
          method: put

  addIssue:
    handler: backend.api.views.generic.issue.add
    events:
      - http:
          path: /api/retro/{retro_id}/issue
          method: post

  voteOrGroupIssue:
    handler: backend.api.views.generic.issue.vote_or_group
    events:
      - http:
          path: /api/retro/{retro_id}/issue/{issue_id}
          method: put

  deleteIssue:
    handler: backend.api.views.generic.issue.delete
    events:
      - http:
          path: /api/retro/{retro_id}/issue/{issue_id}
          method: delete

  addGroup:
    handler: backend.api.views.generic.group.add
    events:
      - http:
          path: /api/retro/{retro_id}/group
          method: post

  voteForGroup:
    handler: backend.api.views.generic.group.vote
    events:
      - http:
          path: /api/retro/{retro_id}/group/{group_id}
          method: put

  deleteGroup:
    handler: backend.api.views.generic.group.delete
    events:
      - http:
          path: /api/retro/{retro_id}/group/{group_id}
          method: delete


plugins:
  - serverless-python-requirements


resources:
  Outputs:
    ApiGatewayId:
      Description: The ID of the API Gateway
      Value:
        Ref : "ApiGatewayRestApi"
